version: "3.8"
services:
  Krypt-compose:
    container_name: vite_hardhat
    entrypoint: /bin/sh
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true