services:
  krypt-compose:
    container_name: krypt_cont
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
        